name: aaa
version: "0.1.0"
license: "GPL-2.0-or-later"
date: 2022-02-09
description: |
    Algorithms for Asynchronous Transducers

authors:
    - name: Collin Bleak
      url: http://www-groups.mcs.st-andrews.ac.uk/~collin/
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Fernando Flores Brito
      url: mailto:[ffb3@st-andrews.ac.uk]
    - name: Feyisayo Olukoya
      url: https://www.abdn.ac.uk/ncs/departments/mathematics/profiles/feyisayo.olukoya/

maintainers:
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Fernando Flores Brito
      url: mailto:[ffb3@st-andrews.ac.uk]

GAP: ">=4.8.0"

needed-pkgs:
    - name: "automata"
      version: ">=0.0.0"
      url: "https://gap-packages.github.io/automata/"
    - name: "digraphs"
      version: ">=0.15.0"
      url: "https://digraphs.github.io/Digraphs"

www: https://gap-packages.github.io/aaa
readme: README.md
packageinfo: https://gap-packages.github.io/aaa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/aaa/releases/download/v0.1.0/aaa-0.1.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BEBO22</span>]   <b class='BibAuthor'>Bleak, C., Elliott, L., Flores Brito, F. and Olukoya, F.</b>,
     <i class='BibTitle'>aaa, Algorithms for Asynchronous Transducers,
             Version 0.1.0</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/aaa">https://gap-packages.github.io/aaa</a></span>.
    </p>
    

bibtex: |
    @misc{ aaa0.1.0,
      author =           {Bleak,  C.  and  Elliott,  L. and Flores Brito, F. and
                          Olukoya, F.},
      title =            {{aaa},   Algorithms   for   Asynchronous  Transducers,
                          {V}ersion 0.1.0},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/aaa}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{aaa}}},
      printedkey =       {BEBO22}
    }

