name: aaa
version: "0.0.0"
license: "GPL-2.0-or-later"
date: 2019-10-09
description: |
    implements algorithms for asynchronous transducers

authors:
    - name: Collin Bleak
      url: http://www-groups.mcs.st-andrews.ac.uk/~collin/
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Fernando Flores Brito
      url: mailto:[ffb3@st-andrews.ac.uk]
    - name: Feyisayo Olukoya
      url: https://www.abdn.ac.uk/ncs/departments/mathematics/profiles/feyisayo.olukoya/

maintainers:
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Fernando Flores Brito
      url: mailto:[ffb3@st-andrews.ac.uk]

GAP: ">=4.8.0"

needed-pkgs:
    - name: "automata"
      version: ">=0.0.0"
      url: "https://gap-packages.github.io/automata/"
    - name: "digraphs"
      version: ">=0.15.0"
      url: "https://digraphs.github.io/Digraphs"

www: https://le27.github.io/aaa/
readme: README.md
packageinfo: https://le27.github.io/aaa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/le27/aaa/releases/download/v0.0.0/aaa-0.0.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BEBO19</span>]   <b class='BibAuthor'>Bleak, C., Elliott, L., Flores Brito, F. and Olukoya, F.</b>,
     <i class='BibTitle'>aaa, implements algorithms for asynchronous transducers,
             Version 0.0.0</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://le27.github.io/aaa/">https://le27.github.io/aaa/</a></span>.
    </p>
    

bibtex: |
    @misc{ aaa0.0.0,
      author =           {Bleak, C. and Elliott, L. and Flores Brito, F. and Olukoya, F.},
      title =            {{aaa},   implements   algorithms  for  asynchronous  transducers,
                          {V}ersion 0.0.0},
      month =            {Oct},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href                               {https://le27.github.io/aaa/}
                          {\texttt{https://le27.github.io/}\discretionary
                          {}{}{}\texttt{aaa/}}},
      printedkey =       {BEBO19}
    }

